### ISSUE TITLE
Detecting failures

### ISSUE THREAD

**Issue by endquote** [sindresorhus/opn#10]
I'm trying to use opn to open a URL. The script is running in a shell process on a remote Ubuntu server. Since there's no GUI, no browser opens, which makes sense. But I can't tell if it worked or not, since the return value of opn is undefined either way, and the callback doesn't get called either way.

Another solution might be to attempt to open lynx...

**Comment by sindresorhus** [comment]
If the callback had been called you should have gotten an error there, but it sounds like the process never exits. Why are you even doing this if you know it's not going to work?

**Comment by endquote** [comment]
The code is running in different environments, some with GUIs and some without.

The callback doesn't get called in either case.

**Comment by sindresorhus** [comment]
The callback is called when the app you started exists. Sounds like it doesn't. The tests works fine on Ubuntu. Also make sure you're using the latest version.

Can you share a testcase that doesn't work?

**Comment by endquote** [comment]
index.js:
```
var opn = require('opn');

var r = opn('http://google.com', null, function(e) {
        console.log(e);
});
console.log(r);
console.log('end');
```

```
[ps437432]$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=12.04
DISTRIB_CODENAME=precise
DISTRIB_DESCRIPTION="Ubuntu 12.04.5 LTS"
[ps437432]$ node -v
v0.12.0
[ps437432]$ npm list
/home/laundryserver/source/test-open
├── open@0.0.5
└─┬ opn@2.0.0
  └─┬ meow@3.1.0
    ├─┬ camelcase-keys@1.0.0
    │ ├── camelcase@1.1.0
    │ └── map-obj@1.0.1
    ├─┬ indent-string@1.2.1
    │ ├── get-stdin@4.0.1
    │ └─┬ repeating@1.1.3
    │   └─┬ is-finite@1.0.1
    │     └── number-is-nan@1.0.0
    ├── minimist@1.1.1
    └── object-assign@2.1.1

[ps437432]$ node index.js 
undefined
end
^C
```

**Comment by sindresorhus** [comment]
Works fine for me. Long shot, but maybe try upgrading to latest node.

There's also no return value, and the `null` is moot as that parameter is optional.
