### ISSUE TITLE
xdg-open doesn't work on GNOME 3.30

### ISSUE THREAD

**Issue by JenteVH** [sindresorhus/opn#104]
```
(node:30702) UnhandledPromiseRejectionWarning: Error: Exited with code 4
    at ChildProcess.<anonymous> (/home/jente/Documents/git/sfinxdatabase/SfinxDatabaseFrontend/node_modules/opn
/index.js:83:13)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:606:12)
(node:30702) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by thr
owing inside of an async function without a catch block, or by rejecting a promise which was not handled with .
catch(). (rejection id: 1)
```

This appears to be a problem with the xdg-open that is shipped.

On line 537 and below:
```
    if gvfs-open --help 2>/dev/null 1>&2; then
        gvfs-open "$1"
    else
        gnome-open "$1"
    fi
```

The problem is that the current version uses neither gvfs-open or gnome-open. Instead it uses `gio open`.

When replacing line 540 with `gio open "$1"` everything works fine.

**Comment by JenteVH** [comment]
The problem is that `gnome-default-applications-properties` is not installed on my distro (`4.18.8-arch1-1-ARCH`) so the shipped xdg-open doesn't recognize gnome3 on this line: `which gnome-default-applications-properties > /dev/null 2>&1  || DE="gnome3"`

**Comment by JenteVH** [comment]
The problem is on this line:
`which gnome-default-applications-properties > /dev/null 2>&1  || DE="gnome3"`
`DE` is not properly being set to gnome3 and instead defaults to just 'gnome'

**Comment by sindresorhus** [comment]
This is a problem with the `xdg-open` and should be reported to https://cgit.freedesktop.org/xdg/xdg-utils/

**Comment by JenteVH** [comment]
@sindresorhus I did figure so much by the end, in any case this repo is still shipping with a non functioning version of xdg-open so it should also be changed at some point when the problem is fixed

**Comment by sindresorhus** [comment]
Yes, I'll update from https://cgit.freedesktop.org/xdg/xdg-utils/ when it's fixed there.

**Comment by JenteVH** [comment]
@sindresorhus Actually it looks like the problem is already fixed.

With this file the problem doesn't happen
https://github.com/freedesktop/xdg-utils/blob/master/scripts/xdg-open.in

**Comment by JenteVH** [comment]
Made PR here for updated version of xdg-open
https://github.com/sindresorhus/opn/pull/105
