### ISSUE TITLE
Not working by default on WSL

### ISSUE THREAD

**Issue by unleashit** [sindresorhus/opn#106]
The script relies on cmd.exe to be in the path in WSL, but it isn't by default (at least for me). Once I added it worked, but I wonder if it would be possible to spawn the open command to bash.exe (or whatever shell is in use) instead of cmd... or would that then require what was being opened to exist on the path?

**Comment by sindresorhus** [comment]
PR welcome to improve this, but WSL is not an officially supported platform, so you're on your own.

**Comment by unleashit** [comment]
Thanks for the reply. Unfortunately I don't have much time for a PR and also never used this library since I submitted the issue. Maybe add it to the docs when you have a chance that you don't support WSL? I think most web developers on Windows are using it by now. For me the problem was a cli tool I was using would silently fail because it was relying on opn to try to launch a browser window for auth reasons.
