### ISSUE TITLE
[Question]: How to test this package in cli-project

### ISSUE THREAD

**Issue by hemal7735** [sindresorhus/opn#109]
Hi @sindresorhus ,

There is a [CLI tool](https://github.com/bnb/good-first-issue) to find good-first-issues for Open Source Projects. It opens the browser with the good-first-issue page.

I'm not sure how to test if the browser was opened properly. Then I looked at the test-case of `opn` package. [You have mentioned that it can not be tested](https://github.com/sindresorhus/opn/blob/master/test.js#L19-L22)

Is it still true that it can not be tested?

**Comment by sindresorhus** [comment]
You cannot really test that it actually opens something, but you could mock the call to `opn` and ensure at least that is correct.
