### ISSUE TITLE
Open using a Windows app referred by its WSL path not supported

### ISSUE THREAD

**Issue by stephen-zhao** [sindresorhus/opn#117]
When I do work on WSL, oftentimes I need to open files using a Windows binary. One example is opening web URLs, where the `$BROWSER` environment variable is passed in as `app` in the args. This variable is set as a WSL path, e.g. `/mnt/d/Program Files (x86)/Google/Chrome/Application/chrome.exe` instead of `D:\Program Files (x86)\Google\Chrome\Application\chrome.exe`. `cmd.exe` fails to find the application because it does not understand the WSL path.

We can add support to this by detecting if the `app` path is a WSL path and convert it to a Windows path if necessary.

Example use-case:
Currently, the npm package `react-dev-utils` makes a call to `opn`, passing in `$BROWSER`.

**Comment by stephen-zhao** [comment]
Here are the proposed changes, I'll put up a pull-request soon:

```diff
	} else if (process.platform === 'win32' || isWsl) {
		...
		if (options.app) {
+			if (isWsl && options.app.startsWith('/mnt')) {
+				options.app = childProcess.execFileSync('wslpath', ['-w', options.app]).toString().trim();
+			}
			cliArguments.push(options.app);
		}
		...
	}
```

**Comment by sindresorhus** [comment]
Sounds good, but should be `options.app.startsWith('/mnt')` => `options.app.startsWith('/mnt/')` and should use `execFile` (with `util.promsifify`) and not `execFileSync`. I would put the logic in a top-level function and call it there.

---

> Should I add test coverage too?

Yes

**Comment by stephen-zhao** [comment]
You can tell I'm new to this haha.

New changes:

```diff
[index.js]
...
+// Converts a path from WSL format to Windows format
+// e.g. /mnt/c/Program Files/Example/MyApp.exe
+//   => C:\Program Files\Example\MyApp.exe
+let wslToWindowsPath = async (path) => {
+	const { stdout, stderr } = await util.promisify(childProcess.execFile)('wslpath', ['-w', path]);
+	return stdout.toString().trim();
+}
...
if (options.app) {
+	if (isWsl && options.app.startsWith('/mnt/')) {
+		options.app = await wslToWindowsPath(options.app);
+	}
	cliArguments.push(options.app);
}
...
```

As for the tests, I added two test cases in `test.js` with a precondition of `isWsl`. The tests don't seem to be set up to run, however. And when I reintroduce ava as a script to run them, all the tests fail due to missing assertions. I'm assuming these aren't complete and are in the works somewhere else?

Anyway, here:

```diff
[test.js]
...
let chromeName;
let firefoxName;
+let chromeWslName;
+let firefoxWslName;
...
} else if (process.platform === 'win32' || isWsl) {
	chromeName = 'Chrome';
	firefoxName = 'C:\\Program Files\\Mozilla Firefox\\firefox.exe';
+	chromeWslName = '/mnt/c/Program Files (x86)/Google/Chrome/Application/chrome.exe';
+	firefoxWslName = '/mnt/c/Program Files/Mozilla Firefox/firefox.exe';
...
+
+if (isWsl) {
+	test('open url in specified windows app given a wsl path to the app', async () => {
+		await open('http://sindresorhus.com', {app: firefoxWslName});
+	});
+
+	test('open url in specified windows app with arguments given a wsl path to the app', async () => {
+		await open('http://sindresorhus.com', {app: [chromeWslName, '--incognito']});
+	});
+}
EOF
```

**Comment by sindresorhus** [comment]
Cool. Submit a pull request ;)

**Comment by sindresorhus** [comment]
> The tests don't seem to be set up to run, however. And when I reintroduce ava as a script to run them, all the tests fail due to missing assertions. I'm assuming these aren't complete and are in the works somewhere else?

They have to be manually run locally and verified. I don't know any way to fully automate it.
