### ISSUE TITLE
Support internet shortcuts

### ISSUE THREAD

**Issue by leesei** [sindresorhus/opn#16]
I've been using a shell script for opening internet shortcut and longed to port it to node.
I'm think of integrating the feature to `opn`, what do you think?

[Gist: Internet shortcuts](https://gist.github.com/leesei/cbb8519c492e3cfca05f)

**Comment by watson** [comment]
Great idea, but wouldn't that be better handled by a separate module that then just depended on opn?

**Comment by arthurvr** [comment]
> Great idea, but wouldn't that be better handled by a separate module that then just depended on opn?

Yeah, that sounds better to me.

**Comment by sindresorhus** [comment]
@leesei Here you go: https://github.com/sindresorhus/open-shortcut-cli :)

**Comment by leesei** [comment]
Oops, you're really quick.
But I might have not make my use case clear.
I have a bunch of `.url` and `.desktop` in my file system.

I currently use this to open them:

```sh
openurl site1.url
openurl site2.desktop
openurl -m site2.desktop
```

I suggest adding this feature to `opn` so I can use `opn` to open any file (at least those I usually open in cli).

**Comment by sindresorhus** [comment]
> But I might have not make my use case clear.

You did, but we're all saying it should be a separate module ;)
