### ISSUE TITLE
bin file?

### ISSUE THREAD

**Issue by dotnetCarpenter** [sindresorhus/opn#21]
I would like to use opn in my package.json.
E.g. `"start": "npm run open & ecstatic . --defaultExt htm"`

**Comment by shinnn** [comment]
Try [`opn-cli`](https://github.com/sindresorhus/opn-cli) :)

**Comment by dotnetCarpenter** [comment]
@shinnn ah I didn't see that. Wish I had before I made a PR #22 . :imp:

**Comment by shinnn** [comment]
FYI https://github.com/sindresorhus/ama/issues/17
