### ISSUE TITLE
Support data URI

### ISSUE THREAD

**Issue by sonnyp** [sindresorhus/opn#24]
`opn data:,Hello%2C%20World!` 

should open the data URI in the browser but does nothing (OS X)

**Comment by sindresorhus** [comment]
Neither does the builtin `open`:

```
❯ open data:,Hello%2C%20World!
The file /Users/sindresorhus/data:,Hello%2C%20World! does not exist.
```

**Comment by sonnyp** [comment]
So it doesn't enter within the scope of opn?

**Comment by sonnyp** [comment]
somehow missed

> Uses the command open on OS X, start on Windows and xdg-open on other platforms.

from https://github.com/sindresorhus/opn#api

**Comment by sindresorhus** [comment]
It will probably work if you explicitly specify a browser in the `app` option.

**Comment by sindresorhus** [comment]
You could also probably hack support for it by detecting a data URI and writing the contents to a tempfile, then open that file.

**Comment by sonnyp** [comment]
@sindresorhus so I take you'd accept a PR?

**Comment by sindresorhus** [comment]
Hmm, not sure. Why do you need it? What are you using it for?

**Comment by sonnyp** [comment]
@sindresorhus I'd use it with pipe, when playing with buffers that contain image data it's quite useful

`./myscript | opn`

**Comment by sonnyp** [comment]
I don't think it's of much usefulness to most users though, I could simply write an `ori` Open URI cli that uses opn and a temporary file as you suggested

**Comment by sindresorhus** [comment]
I think it would be useful to https://github.com/sindresorhus/opn-cli. PR welcome to add stdin support there using https://github.com/sindresorhus/get-stdin and https://github.com/sindresorhus/temp-write.

**Comment by sonnyp** [comment]
https://github.com/sindresorhus/opn-cli/pull/6
