### ISSUE TITLE
ES2015ify

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/opn#30]
In for es2015ifying this module and dropping all the dependencies? Or just a little bit too early?

**Comment by sindresorhus** [comment]
I don't think it's time yet. Lots of people depend on this module. Not worth doing another breaking release yet. Keeping this open so I don't forget.

**Comment by Ginden** [comment]
I suggest dropping support for Node 0.10 when it reaches end of life ([October 2016](https://raw.githubusercontent.com/nodejs/LTS/master/schedule.png)) and remove `pinkie-promise` dependency then (as Node 0.12 support native `Promise`).
