### ISSUE TITLE
Reuse existing tab in Chrome

### ISSUE THREAD

**Issue by hellboy81** [sindresorhus/opn#31]
I need following functionality:

- If tab with `url` is opened in Browser - ist should be only activated. 
- No new tab with the same url should be opened.

**Comment by sindresorhus** [comment]
If Chrome has a runtime option for that you could pass it as an app argument, see the docs. You could probably use AppleScript to achieve what you want, but that's way out of scope for this module.

**Comment by ricsam** [comment]
Will just leave this one here from one of the referenced issues:

```
const openBrowser = require('react-dev-utils/openBrowser');
openBrowser('http://localhost:6006');
```

**Comment by karlhorky** [comment]
> You could probably use AppleScript to achieve what you want, but that's way out of scope for this module.

@sindresorhus has your opinion changed on this?

Just discussing in ExiaSR/better-opn#2 about contributing that to this project, but I guess you don't want that in this module, correct?

**Comment by vincerubinetti** [comment]
> way out of scope for this module.

Would be really nice to have this. I know this package intends to be a general purpose "open" command and not a browser-specific one, but I would bet a huge portion of people are coming to this package for that functionality. If you have anecdotal evidence that many/most people are coming to this package for the browser opening, I'd urge you to reconsider this.

In the meantime, anyone know off the top of their head what Chrome arguments you could use to, say, open a vite dev localhost:5173 server in a tab or re-use an existing tab?
