### ISSUE TITLE
fails to open multiple URLs on Edge "coldstart"

### ISSUE THREAD

**Issue by LucaBlackDragon** [sindresorhus/opn#32]
If MS Edge is closed by the time opn is invoked, running this script results in only the first URL being loaded:
```js
const opn = require('opn');
const urlList = ['https://github.com/sindresorhus/opn', 'https://www.google.com'];
urlList.map(opn); // assuming Edge is the system default browser
```
If another browser is used (e.g. firefox) it works as expected (i.e. it opens multiple instances of the browser if it's closed, or it opens multiple tabs inside the same browser instance if there is one available - this is true for Edge too).

**Comment by sindresorhus** [comment]
Probably a race condition with you calling Edge multiple times at once without waiting for the first call to complete. Try waiting for the Promise to resolve before opening the second URL.
