### ISSUE TITLE
Unnecessary quotation marks?

### ISSUE THREAD

**Issue by ScottFreeCode** [sindresorhus/opn#34]
On Windows, this is passing `'""'` as the first argument to `start` to avoid `start` interpreting a quoted filename as the title of a console window. As it turns out, this seems to be automatically escaped just like the filename itself: if I run `opn("cmd")`, I get a cmd window with the title `\\` (I guess the quotes disappear but the attempt to escape them does not), whereas if I change `'""'` to just `''` or `""` I get a cmd window with no title as expected. This does not appear to affect running any actual file/url one way or the other (`opn("some file")` still works right), so it doesn't really matter as far as functionality, but I wanted to point it out as far as theoretical correctness goes. File under "fun fact" I guess.

(It also seems that instead of a blank window title, an actual window title could be given; but I'm not sure that's useful, between the fact that there are better ways to open a console from Node and the fact that a blank window title would be odd but not confusing whereas any name hardcoded in `opn` could be irrelevant in whatever hypothetical usage did cause `cmd` to be opened through `opn`.)

**Comment by sindresorhus** [comment]
You might be right, but it was [added for a reason](https://github.com/sindresorhus/opn/pull/26), and it wouldn't be worth changing it now, in case it has some unforseen downsides.

**Comment by ScottFreeCode** [comment]
To clarify, I don't mean that the argument could be removed altogether -- that would cause `start` to interpret the filename as the name of a new console window (which is, as I understand it, why it had to be added); I mean that using a string containing `""` seems to escape the double-quotes and wrap them in another pair of quotes like `start "\"\""`, whereas the intention of calling `start ""` seems to be effected by using an empty string as the argument instead.

Although you're right -- it's working now and I don't know for sure that this obvservation holds for all versions of Node and all versions of Windows; without some way to test it automatically it's hard to say for sure that the behavior I'm seeing is consistent everywhere.

**Comment by ScottFreeCode** [comment]
Actually did think of a potential automated test just now -- we could open a `.bat` script that takes some action to indicate success, then wait/watch for that action with an appropriate timeout (might need a little tuning) to be sure the batch script ran. Wouldn't necessarily uncover all possible issues with opening files, but at any rate would demonstrate that `start` is not misinterpreting the filename as a console window name and failing to run the file.
