### ISSUE TITLE
Dependency on Linux file-system execute bit for xdg-open script breaks in some scenarios (VS Code)

### ISSUE THREAD

**Issue by DavidAnson** [sindresorhus/opn#38]
Please see https://github.com/DavidAnson/vscode-markdownlint/issues/4 for more details.

Briefly, the workflow for publishing a [VS Code](https://code.visualstudio.com/) extension from Windows and running it on Linux does not preserve the `execute` bit for the `xdg-open` script, so `opn` fails when called on Linux.

@jdumas proposes a change to `opn` in the above issue that may help (but I don't have the platform expertise to say for sure).

**Comment by sindresorhus** [comment]
This is either a VC Code or npm issue.
