### ISSUE TITLE
Open iTerm and run command inside

### ISSUE THREAD

**Issue by kingaiakab** [sindresorhus/opn#40]
I have tried to open iTerm and run a command inside, but it fails. Here is the snippet:

`opn('ls', { app: '/Applications/iTerm 2.app' });`

It tries to open the file named `ls`.

**Comment by sindresorhus** [comment]
> It tries to open the file named ls.

Yes, that's how it works. If you want to run custom commands you need to find app specific ways to do it: http://stackoverflow.com/questions/32675804/how-do-i-execute-a-command-in-an-iterm-window-from-the-command-line
