### ISSUE TITLE
How can I close an application ?

### ISSUE THREAD

**Issue by mca22120** [sindresorhus/opn#43]
Hello,

Thanks to your job I'm able to open an application (an Excel file in my case).
Do you know something to close this Excel application after some processing that I need to do ?

Thank you,
Mathieu

**Comment by SamVerschueren** [comment]
What about cmd+q? Don't really understand your question...

**Comment by mca22120** [comment]
More precisely, I need to know the PID of the process that I launch.
If I know this PID, I can close the application with womething like this : https://www.npmjs.com/package/taskkill

**Comment by sindresorhus** [comment]
```js
opn('http://sindresorhus.com').then(cp => {
  // PID
  console.log(cp.pid);

  // Close the app
  cp.kill();
});
```

**Comment by mattcheah** [comment]
Hi @sindresorhus,
Is this supposed to close the opened window when the node app is closed? If so, it's not working on windows at least. In fact, according to `console.log(cp.pid)`, the PID doesn't even exist but the opened window remains open. Is this a windows bug or am I not understanding how it is supposed to work?

**Comment by ncuillery-youitv** [comment]
@mattcheah I second that, `cp` is the current process (the node process), not the one that has been spawn.
Therefore, killing it has no effect on the opened window.

**Comment by doverradio** [comment]
Hello guys, I also am facing issue on this.  I get how to open a program but is there really no way to close it once it's opened?

**Comment by stefanocudini** [comment]
as long as xdg-open is used I think it is not possible to know the pid of the child :(
https://stackoverflow.com/questions/60517108/how-to-kill-subprocess-of-xdg
