### ISSUE TITLE
Respect Chrome Devtools URLs

### ISSUE THREAD

**Issue by willviles** [sindresorhus/opn#45]
I'm building a simple [debugging tool for the awesome Node API framework Lux](https://github.com/postlight/lux/pull/685), which uses `node --inspect`. Node's new built in inspector spits back a `chrome-devtools://` url, which I'd like to open automatically.

However, opn doesn't seem to respect `chrome-devtools` URLs, even when I pass Google Chrome explicitly as the application to open. I'm therefore resorting to using a MacOSx-only solution of opening the URL using an `osascript`.

Is there an easy fix for whitelisting `chrome-devtools` URLs?

**Comment by sindresorhus** [comment]
It doesn't seem like Chrome allows it.

This works:

```
open -a "Google Chrome Canary" --args --new-window "https://sindresorhus.com"
```

This does not:

```
open -a "Google Chrome Canary" --args --new-window "chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:9229/9f6677d6-1af0-424d-9421-388685906814"
```

**Comment by willviles** [comment]
Hmm, yes. I've [created an issue](https://productforums.google.com/forum/#!topic/chrome/0wQOfl-UEAk;context-place=forum/chrome) on the Chrome help forum.

**Comment by willviles** [comment]
So, I can't find a cross-platform solution for opening chrome-devtools URLs and seeing as this isn't an opn problem I'll close this issue 👍
