### ISSUE TITLE
Usage with React

### ISSUE THREAD

**Issue by necrodevz** [sindresorhus/opn#46]
Hi, I'd like to use this library in react for a dashboard I'm building for my company. The problem is that I cannot seem to get this to work in React using ES6 syntax. Is there any way I can get this to work? Or if not, could you recommend any alternatives?

**Comment by SamVerschueren** [comment]
And what exactly are you trying to do? This is not a front-end module, it's a node module.

**Comment by necrodevz** [comment]
Apologies. I'm trying to launch a link in a specific browser. Can you give any advice on how to do so? for example, I'd like to launch the first link in IE, but the second in Firefox.
