### ISSUE TITLE
How to know what app name to use

### ISSUE THREAD

**Issue by chris-orchard** [sindresorhus/opn#48]
I see the app can be specified with `{app: 'name'}`

How do I know or look up what the app name need to be to correspond to a particular program?

I want to open a url with Chrome Canary instead of my default browser (Chrome) but I've tried various names without it working. This is on Windows but is there a OS generic way to check the app names?

**Comment by sindresorhus** [comment]
The app name is the binary/bundle name. Just look up what it's called on the file system.

**Comment by chris-orchard** [comment]
For me on Windows it seems that `opn(url, {app: 'chrome'})` actually opens in Canary which is what I want. `opn(url)` opens in Chrome.

I'm not sure why it works like this but it might be down how Canary app path is set in the Windows registry as detailed here: http://www.muratsutunc.com/tips/how-to-launch-chrome-from-cmd.html
