### ISSUE TITLE
Cannot detect when a browser tab has been closed.

### ISSUE THREAD

**Issue by andipavllo** [sindresorhus/opn#49]
After I open an URL in a new tab, I need to wait until the tab has been closed in order to execute some operations. It seems that `opn` cannot detect it and you need to kill the whole browser processes in order to continue the code execution (supposing that `{wait: true}` has been used).

Tried with Chrome and Firefox, same result. It's probably hard to detect the `pid` of the opened tab as the browser (at least Chrome in this case) seems to create a new child process for the tab, which is not detected by `opn`.
I'm wondering if there is any workaround for this.

**Comment by sindresorhus** [comment]
You could maybe use AppleScript or AutoHotkey to to poll whether the tab still exists. I don't think there's an easy universal solution to this however.
