### ISSUE TITLE
Have the promise resolve after the browser has been opened ? 

### ISSUE THREAD

**Issue by fabulousduck** [sindresorhus/opn#51]
currently there is no option to have the promise fulfill when the browser has been opened. Only either when the browser has been exited or immediately after execution by setting wait to false.
Is there a way to figure out when it has been successfully opened so i can activate a macro when its happened ?

**Comment by sindresorhus** [comment]
There's no easy way to know when it's been opened. You could check yourself with AppleScript or similar or less accurately, check if the process exists. None of these solutions makes sense for this module though.
