### ISSUE TITLE
Support Electron

### ISSUE THREAD

**Issue by blahah** [sindresorhus/opn#57]
@sindresorhus you recently [helped me debug where opn wasn't working in Electron](https://github.com/codeforscience/sciencefair/issues/101#issuecomment-311958641).

It would be nice if `opn` *could* handle Electron seamlessly. Any interest in a PR adding support for it?

Specifically:

- detect if run within Electron
- if so call the appropriate [`shell.open*`](https://github.com/electron/electron/blob/master/docs/api/shell.md#shellopenitemfullpath) method

**Comment by sindresorhus** [comment]
How would the options be handled?

**Comment by blahah** [comment]
@sindresorhus good question.

If `options.app` were specified, `child_process.spawn` would have to be used.
If not, the `shell.open` APIs.

**Comment by sindresorhus** [comment]
Yeah, I guess that would be ok as long as the behavior is documented in the readme.

**Comment by hyalkaf** [comment]
Using shell in electron, you cannot detect when the file will be closed as there is no wait option unlike in opn.

**Comment by sindresorhus** [comment]
I changed my mind. This is just going to cause problems. `opn` should work in Electron now if you need the waiting. I would also recommend opening a feature request on Electron about being able to wait.
