### ISSUE TITLE
Support pkg

### ISSUE THREAD

**Issue by kMeillet** [sindresorhus/opn#61]
It could be nice if "opn" package support Zeit "pkg" :) .

Currently, building a cross-platform packages with "pkg" don't work well with "opn", it do nothing and browser don't open : 

```
Error: spawn /snapshot/deploy/node_modules/opn/xdg-open ENOENT 
```

I will try some solution and update the issue, but i think "pkg" doesn't work with bash script (xdg-open is not packaged).

**Comment by sindresorhus** [comment]
This would be better as an issue on `pkg`. This module is just a normal Node.js module. It's up to `pkg` to be compatible with the ecosystem, not the other way around.
