### ISSUE TITLE
Open applications without using file (like outlook)

### ISSUE THREAD

**Issue by aumerhadi** [sindresorhus/opn#69]
Is it possible to open application with out file ? like outlook or cmd or putty, these application don't require file to open it (not like photoshop or MS word)
and what is the code to do that?

**Comment by aumerhadi** [comment]
I tried this code and it open the application but the code executing stuck until I close the application 
`opn( '', {app: 'thunderbird'});`

**Comment by sindresorhus** [comment]
The app name really depends on the platform too, see: https://github.com/sindresorhus/opn/blob/ebae31e9117ae3ca5c9ee642bafa9449f1e237c2/test.js#L8-L17

You might want to set `{wait: false}`, see docs.
