### ISSUE TITLE
EACCESS on Linux - `xdg-open` does not have execute permission

### ISSUE THREAD

**Issue by grinnery** [sindresorhus/opn#70]
Installing the package with `npm i opn -S`  (or directly from git repo) does not preserve executable attribute on `xdg-open`, resulting in `EACCESS` when opn-ing URLs.

**Comment by sindresorhus** [comment]
Probably related to https://github.com/npm/npm/issues/18324. Keeping this open until that is resolved.

**Comment by EvanCarroll** [comment]
Why are you even shipping your own version of `xdg-open`. Can't we delegate to `/usr/bin/env` and use the system's version if present?

**Comment by kevva** [comment]
Because not all systems has `xdg-open`. It's probably easier to track down issues by shipping a local version of it.

**Comment by sindresorhus** [comment]
https://github.com/npm/npm/releases/tag/v5.4.1
> This is a very small bug fix release to fix a problem where permissions on installed binaries were being set incorrectly.
