### ISSUE TITLE
Arrow functions causing compatibility issues

### ISSUE THREAD

**Issue by derrickb** [sindresorhus/opn#73]
Hello,

I see in 5.0.0 that arrow functions were introduced.  This unfortunately made the module incompatible with the Chromium Embedded Framework version I have to use for my product.
I'd understand if ES6 compatibility is required going forward, but it'd be great to keep using whatever improvements you introduce without needing to keep my own local edits or being stuck on an old version. As such, I'd ask that you reconsider.

Thank you!

**Comment by kevva** [comment]
You could always transpile the module first using something like Babel. We won't support anything that isn't supported by Node.js itself.

**Comment by kevva** [comment]
You'll probably hit this issue many times in case you're not transpiling. In case you're using `webpack` there's https://github.com/samverschueren/babel-engine-plugin which only transpiles the modules which needs it.

**Comment by derrickb** [comment]
Thank you but my setup is pretty lean and I'd like to keep it that way... lots of plain JavaScript, and only a few key node modules (including opn).  And then grunt for combining things together.  Would rather avoid going down the webdev tools rabbit hole! I'll stick with opn 4.0.2 as it's working fine.

FWIW in case you're interested, my product is an extension for Adobe Photoshop.  Adobe has switched their extension platform to use CEF along with a local Node process for utilities and such.  Unfortunately this means I'm locked into whatever CEF version that shipped with specific versions of Photoshop.

**Comment by kevva** [comment]
I see. Shame they didn't use https://electron.atom.io/ instead. Good luck with your app :).
