### ISSUE TITLE
It's possible start OPN compiled by Browserify in domReady?

### ISSUE THREAD

**Issue by smachs** [sindresorhus/opn#76]
Due to some mandatory policies of my application I need a button to click a new browser is open. 

From my browserify final script in my HTML this error is returned to me 

```
index.js:74 Uncaught TypeError: childProcess.spawn is not a functionmodule.exports @ index.js:74
(anonymous function) @ pre-build-upload-company-parallel-and-branch.js:5
r.event.dispatch @ jquery-3.2.1.min.js:3
q.handle @ jquery-3.2.1.min.js:3
```
My pre-build browserify script
```
require('domready')(function () {
    $("#openLinkBrowserRedirect").click(function () {
        const opn = require('opn');

        opn('http://google.com', { app: 'firefox' });

        console.log("sucess!");
    });
})
```
I could not find anything here it is possible or not through an event in my front-end execute `opn();`

Thanks!!

**Comment by sindresorhus** [comment]
This module is for Node.js, not the browser.

**Comment by smachs** [comment]
@sindresorhus It would be uncomfortable for you to indicate me similar `module` that allows this action in the `browser`?
