### ISSUE TITLE
Opening a URL wipes Firefox settings

### ISSUE THREAD

**Issue by iONinja** [sindresorhus/opn#78]
Hi there,

I'm using Ubuntu 14.04 with Firefox 54.0 (64-bit).
I used `opn` to open a URL in Firefox, and then closed the browser.

When I opened Firefox afterwards, it forgot all my settings, theme, etc. Although, it remembered by account and history.

So what's going on here?

**Comment by sindresorhus** [comment]
`opn` is just using `xdg-open` to open the URL. Just try it directly with https://github.com/sindresorhus/opn/blob/master/xdg-open and you'll see the same problem. You should report the issue to `xdg-open` instead.

**Comment by constgen** [comment]
If I was a developer of `opn`, I would report an issue to `xdg-open` by myself becuase I know that it causes an issue in my library.

**Comment by iONinja** [comment]
@sindresorhus 

Okay, thanks for the reply.
How exactly would I go about contacting the developer? I have looked for a GitHub repo, but have found none.

**Comment by sindresorhus** [comment]
@constgen If I had unlimited time for open source work, yes, but I'm already swamped with hundreds of notifications/issues/PRs every day.

**Comment by sindresorhus** [comment]
@iONinja Found the issue tracker after some looking: https://bugs.freedesktop.org/buglist.cgi?component=xdg-utils&product=Portland&resolution=---

**Comment by iONinja** [comment]
@sindresorhus 

Great, thanks!

**Comment by constgen** [comment]
@sindresorhus Now I see it is complecated
