### ISSUE TITLE
specify port number

### ISSUE THREAD

**Issue by intouchdentistry** [sindresorhus/opn#82]
How to specify a port number? E.g. localhost:3000

**Comment by sindresorhus** [comment]
The issue tracker is for actual issues, not support requests. But yes, you specify it exactly like that: `http://localhost:3000`.

**Comment by intouchdentistry** [comment]
I got it to run using 

const child = require('child_process')

// run a terminal command
child.exec('start chrome.exe "http://localhost:3000', [], (error, stdout, stderr) => {
  if (error) {
    throw error
  }
  console.log(stdout)
})
