### ISSUE TITLE
Opens Chrome window w/o site loaded

### ISSUE THREAD

**Issue by homakov** [sindresorhus/opn#83]
It used to work but last few days opn just opens chrome without loading the site. Maybe some chrome update broke it?

**Comment by sindresorhus** [comment]
Try restarting Chrome (Or even your machine). It usually happens when Chrome updates and you haven't restarted it yet. Happens to me when trying to open links from Slack and Notes too.

**Comment by SamVerschueren** [comment]
Yes, it's OS or Chrome related. Happens to me as well...

**Comment by dwalintukan** [comment]
I am receiving the same thing. Sometimes nothing opens.

**Comment by SamVerschueren** [comment]
@sindresorhus think we can close this one. It's not related to the package so I don't believe we can fix it.
