### ISSUE TITLE
I can't open edge or internet explorer browser

### ISSUE THREAD

**Issue by amorenew** [sindresorhus/opn#85]
I wonder how could I open a URL in edge or internet explorer browser
OS: Windows 10

```
 opn https://travel-angular-78148.firebaseapp.com -- internet explorer
 opn https://travel-angular-78148.firebaseapp.com -- internet-explorer
 opn https://travel-angular-78148.firebaseapp.com -- 'internet-explorer'
 opn https://travel-angular-78148.firebaseapp.com -- 'internet explorer'
 opn https://travel-angular-78148.firebaseapp.com -- 'internet explorer 11'
 opn https://travel-angular-78148.firebaseapp.com -- 'microsoft internet explorer 11'
 opn https://travel-angular-78148.firebaseapp.com -- 'microsoft internet explorer'
```
nothing worked for me

**Comment by xxczaki** [comment]
Hi, I’m not a Windows user, but try opening `ie` or `ie11`. Hope that will help :smile:

**Comment by amorenew** [comment]
@xxczaki I found Internet Explorer
-- iexplore

still I can't open edge

**Comment by xxczaki** [comment]
Have you tried `MicrosoftEdge`? That's the name of Edge's .exe file.

**Comment by amorenew** [comment]
Yes not opening
![image](https://user-images.githubusercontent.com/2842459/36630025-4e76b4a4-1970-11e8-9fde-e2bc2d2ea951.png)
But from StackOverflow this is the way for opening edge
`start microsoft-edge:http://www.cnn.com`
still `opn https://travel-angular-78148.firebaseapp.com -- microsoft-edge` not open

**Comment by TheDancingCode** [comment]
This seems to work: `opn -- microsoft-edge:https://travel-angular-78148.firebaseapp.com`.

**Comment by amorenew** [comment]
so in microsft edge we need url after the browser name
-- microsoft-edge:my_url
awesome

**Comment by hajimurtaza** [comment]
> so in microsft edge we need url after the browser name
> -- microsoft-edge:my_url
> awesome

Were you able to use this in an angular app. If yes Please could you post how you managed to do it?

**Comment by amorenew** [comment]
@hajimurtaza it works that way when I tried it but it is not working for you open a new issue

**Comment by amorenew** [comment]
it still working 
`opn -- microsoft-edge:https://travel-angular-78148.firebaseapp.com`

**Comment by pungggi** [comment]
for developers from the future..
use `msedge` for the new edge with chromium..
