### ISSUE TITLE
Does not open on multiple requests within a loop

### ISSUE THREAD

**Issue by joe-oli** [sindresorhus/opn#89]
Simple example. the array contains 3 urls;
It iterates thru, logs the urls correctly but only the first url is  opened.

```
urlsArray.forEach(function(urlLine){
        opn(urlLine);  //for each url... launch in Browser
        console.log(urlLine);
});
```

My environment is Windows / default Browser chrome
Node v 6.11.5

**Comment by joe-oli** [comment]
**work around -** 
opn does not do what i want, use an o/s cmd instead.
 
```
var childProc = require('child_process');
urlsArray.forEach(function(urlLine){
        var cmd = "start chrome " + urlLine
        childProc.execSync(cmd);
});
```

**Comment by TheDancingCode** [comment]
Can't seem to reproduce this. What does your `urlsArray` look like?
