### ISSUE TITLE
Process never exits

### ISSUE THREAD

**Issue by kevva** [sindresorhus/opn#9]
For some reason, the process never exits when opening something, even without the callback. See https://github.com/kevva/github-search-repos/blob/master/cli.js#L51 for an example.

Happens with 0.10, 0.12 as well as io.js 1.6.4 on Ubuntu (running inside a VM). It doesn't seem to happen in Windows though.

**Comment by sindresorhus** [comment]
Weird, I remember this working at some point... Annoying that's there no way to unit test this module...

Can you try out https://github.com/sindresorhus/opn/commit/9c05297a5e292617f855f6d0ded2e40a2be972da and let me know?

**Comment by kevva** [comment]
That works great.

**Comment by cperryk** [comment]
Seems like this issue is happening again. Running this simple script:
```
const opn = require('opn');
opn('http://www.google.com');
```
The process never exits. I'm on Node 5.2.0 on OS X 10.11.

**Comment by shinnn** [comment]
@cperryk The waiting behavior is now explicitly enabled by default. https://github.com/sindresorhus/opn/pull/14

**Comment by whyboris** [comment]
For reference, just do this:
```js
opn(filePath, { wait: false });
```
