### ISSUE TITLE
opn not working on live server

### ISSUE THREAD

**Issue by jay123789** [sindresorhus/opn#96]
I'm trying to open browser window its working on local host ,when i posting that code on server and trying to open its not opening .
 const authorizeUrl = oAuth2Client.generateAuthUrl({
    access_type: 'offline',
    scope: SCOPES,
  });
  console.log(authorizeUrl,'123')
   // open the browser to the authorize url to start the workflow
//   opn(authorizeUrl, {wait: false}).then(cp => cp.unref());
})

**Comment by sindresorhus** [comment]
I'm not sure what you're doing wrong, but there's not much I can do.
