### ISSUE TITLE
Show existing tab and reload it

### ISSUE THREAD

**Issue by bastienrobert** [sindresorhus/opn#99]
On opn call, if there's already a tab with the same URL, is there an option to show this existing tab in first ground and to reload it ? If not, is there any other way to do it or any enhancement planned ?

Quick example (not sure it's really great explained): if i'm calling `opn('https://google.com')` and google is already opened on Chrome, then chrome will show with the tab where's google.com and it'll reload it.

**Comment by bastienrobert** [comment]
I found a solution on macOS with Google Chrome, using an AppleScript script inspired by `create-react-app` by Facebook. It's looking like this: https://gist.github.com/bastienrobert/16cb86e3683e4804b9e0b78e71b8732f.

**Comment by DemonCloud** [comment]
@bastienrobert has any solution for Windows 10?
